services:
  adonis_app:
    container_name: padel-tournament-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3333:3333'
